### ISSUE TITLE
Push Notification Failed

### ISSUE THREAD

**Issue by Poory1** [carlreinecken/piqchat-inbox-server#3]
Hey, thanks for the great PWA. My docker compose log indicate that there is an error with Push Notifications. I didnt receive one when I got a PIQ. 

```
sendPushNotification failed with "Error: No subject set in vapidDetails.subject." with recipient LTYtw...
```

**Comment by carlreinecken** [comment]
Thanks for the question! `vapidDetails.subject` refers to the environment variable `PUSH_VAPID_CONTACT`. You need to set a value to an email adress or website where the push service can contact you if something is not working. The example.env has more info.

I will look into improving the error message!
